### ISSUE TITLE
extract lower crates to unrust/xxx

### ISSUE THREAD

**Issue by jice-nospam** [unrust/unrust#58]
I started using the lower crates (webgl, uni-app, uni-glsl) for another project.
Do you think they're stable enough to be moved to independant projects like unrust/webgl, unrust/uni-app and unrust/uni-glsl ?
This makes it possible to reference them directly in the Cargo.toml through git URLs instead of having to clone the whole unrust project.

**Comment by edwin0cheng** [comment]
Although i think these crate still not stable enough, but it is okay to move to independent projects. 
Do you want to do it, or wait for me (im quite busy in these 2 months) to move ?

**Comment by jice-nospam** [comment]
no problem, I'll do it. Once you feel they're stable enough, we can push them on crates.io. Until then I'm fine with using directly the github URLs.
I'll create the new projects here and send a pull request for the unrust main project

**Comment by jice-nospam** [comment]
Ok I created the projects but I can't submit the PR for unrust right now as it doesn't compile. It seems there's a bug in the last nightly rustc. Investigating...

**Comment by edwin0cheng** [comment]
Is it solved ?

**Comment by jice-nospam** [comment]
yes
